Release 23.06

diff --git a/docker/Dockerfile.xfce.postman b/docker/Dockerfile.xfce.postman
--- a/docker/Dockerfile.xfce.postman
+++ b/docker/Dockerfile.xfce.postman
@@ -331,6 +331,11 @@ RUN \
         libxss1 \
         libxtst6
 
+### The 'Postman' version is locked to '10.13.6', the last one that still includes 'Scratch Pad'.
+### The first release with this locking is '23.06'.
+### The last 'Postman' version containing 'Scratch Pad' is '10.13.6'.
+### The first 'Postman' version not containing 'Scratch Pad' is '10.14.2' (since May 15, 2023).
+### Warning! File 'postman-10.13.6-linux-x64.tar.gz' must be put into 'g3-cache', downloading is prohibited.
 RUN \
     --mount=type=cache,from=stage_cache,sharing=locked,source=/var/cache/apt,target=/var/cache/apt \
     --mount=type=cache,from=stage_cache,sharing=locked,source=/var/lib/apt,target=/var/lib/apt \
@@ -338,9 +343,12 @@ RUN \
     POSTMAN_VERSION="${ARG_POSTMAN_VERSION}" \
     POSTMAN_DISTRO="${ARG_POSTMAN_DISTRO}" \
     &&  if [ ! -s "/tmp/g3-cache/postman/postman-${POSTMAN_VERSION}-${POSTMAN_DISTRO}.tar.gz" ] ; then \
-            wget --show-progress --progress=bar:force:noscroll \
-                -q "https://dl.pstmn.io/download/latest/linux64" \
-                -P "/tmp/g3-cache/postman/postman-${POSTMAN_VERSION}-${POSTMAN_DISTRO}.tar.gz" ; \
+            echo "GUARD ERROR: Downloading 'Postman' is prohibited. Put file 'postman-10.13.6-linux-x64.tar.gz' into 'g3-cache'." && exit 1 ; \
+            ### Warning! The next code would download the real latest version
+            ### and store it under the name of the version '10.13.6'!
+            # wget --show-progress --progress=bar:force:noscroll \
+            #     -q "https://dl.pstmn.io/download/latest/linux64" \
+            #     -P "/tmp/g3-cache/postman/postman-${POSTMAN_VERSION}-${POSTMAN_DISTRO}.tar.gz" ; \
         fi \
     &&  tar xzf "/tmp/g3-cache/postman/postman-${POSTMAN_VERSION}-${POSTMAN_DISTRO}.tar.gz" -C "${POSTMAN_PATH}" \
     &&  ln -s "${POSTMAN_PATH}/Postman/Postman" "/usr/local/bin/postman" \
diff --git a/docker/hooks/cache b/docker/hooks/cache
--- a/docker/hooks/cache
+++ b/docker/hooks/cache
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 ### @accetto, September 2022
-### updated: January 2023
+### updated: June 2023
 
 echo -e "\n==> EXECUTING @$(date -u +'%Y-%m-%d_%H-%M-%S'): ${0} $@\n"
 
@@ -154,6 +154,7 @@ cache_postman() {
     local target_path="${_cache}/${section}"
     local target=""
     local file=""
+    local source=""
 
     mkdir -p "${target_path}"
 
@@ -163,7 +164,38 @@ cache_postman() {
     ### warning, this is specific for 'postman'
     source_url="${source_base_url}"
 
-    refresh_file "${section}" "${file}" "${source_url}" "${target}"
+    ### Warning! The following implementation is specific to 'Postman' (since May 15, 2023).
+
+    ### The 'Postman' version is locked to '10.13.6', the last one that still includes 'Scratch Pad'.
+    ### The last 'Postman' version containing Scratch Pad is '10.13.6'.
+    ### The first 'Postman' version not containing Scratch Pad is '10.14.2' (since the release 23.06).
+
+    ### original implementation (till the release 23.06)
+    # refresh_file "${section}" "${file}" "${source_url}" "${target}"
+
+    ## new implemntation (since the release 23.06)
+    if [[ "${POSTMAN_VERSION}" != "10.13.6" ]] ; then
+
+        echo "GUARD ERROR: Postman version ${POSTMAN_VERSION} not matching the required value '10.13.6'."
+        return 1
+    else
+        if [[ ! -s "${target}" ]] ; then
+
+            source="${_shared_cache_path}/${section}/${file}"
+
+            ### only copying from the local 'g3-cache' is supported
+            if [[ -s "${source}" ]] ; then
+
+                echo -e "${_mark} refreshing section '${section}' by copying shared file '${file}'\n"
+                cp "${source}" "${target}"
+            else
+                echo -e "${_mark} section '${section}': GUARD ERROR: Downloading 'Postman' is prohibited. Put file 'postman-10.13.6-linux-x64.tar.gz' into 'g3-cache'."
+                return 1
+            fi
+        else
+            echo -e "${_mark} hit file '${file}' in section '${section}'"
+        fi
+    fi
 }
 
 ### ==========
@@ -179,22 +211,28 @@ main() {
     if [[ "${FEATURES_VNC}" == "1" ]] ; then
 
         cache_tigervnc
+        if [[ $? -ne 0 ]] ; then return 1; fi
     fi
 
     if [[ "${FEATURES_NOVNC}" == "1" ]] ; then
 
         cache_novnc
+        if [[ $? -ne 0 ]] ; then return 1; fi
+
         cache_websockify
+        if [[ $? -ne 0 ]] ; then return 1; fi
     fi
 
     if [[ "${FEATURES_NODEJS}" == "1" ]] ; then
 
         cache_nodejs
+        if [[ $? -ne 0 ]] ; then return 1; fi
     fi
 
     if [[ "${FEATURES_POSTMAN}" == "1" ]] ; then
 
         cache_postman
+        if [[ $? -ne 0 ]] ; then return 1; fi
     fi
 
     echo
