more die-fast error handling

diff --git a/docker/hooks/build b/docker/hooks/build
--- a/docker/hooks/build
+++ b/docker/hooks/build
@@ -70,7 +70,8 @@ main() {
 
         nodejs | nodejs-* | nodejs-current | nodejs-current-* )
 
-            ### no quotes around 'params'
+            ### no quotes around ${params}!
+            set -x
             docker build ${params} \
                 -f "${DOCKERFILE_PATH}" \
                     --build-arg BASEIMAGE="${BASEIMAGE}" \
@@ -104,7 +105,11 @@ main() {
                     ${FEATURES_VSCODE:+--build-arg ARG_FINAL_STAGE_BASE="stage_vscode"} \
                     \
                 -t "${DOCKER_REPO}":"${DOCKER_TAG}" "${_build_context}"
+            
+            exit_code=$?
             set +x
+            
+            if [[ ${exit_code} -ne 0 ]] ; then die "Failed to build image '${DOCKER_REPO}:${DOCKER_TAG}'" ${exit_code} ; fi
             ;;
 
         ### --------------------------
@@ -113,8 +118,8 @@ main() {
 
         postman | postman-* )
 
+            ### no quotes around ${params}!
             set -x
-            ### no quotes around 'params'
             docker build ${params} \
                 -f "${DOCKERFILE_PATH}" \
                     --build-arg BASEIMAGE="${BASEIMAGE}" \
@@ -146,7 +151,11 @@ main() {
                     ${FEATURES_POSTMAN:+--build-arg ARG_FINAL_STAGE_BASE="stage_postman"} \
                     \
                 -t "${DOCKER_REPO}":"${DOCKER_TAG}" "${_build_context}"
+            
+            exit_code=$?
             set +x
+            
+            if [[ ${exit_code} -ne 0 ]] ; then die "Failed to build image '${DOCKER_REPO}:${DOCKER_TAG}'" ${exit_code} ; fi
             ;;
 
         ### -------------------------
@@ -155,8 +164,8 @@ main() {
 
         python | python-* )
 
+            ### no quotes around ${params}!
             set -x
-            ### no quotes around 'params'
             docker build ${params} \
                 -f "${DOCKERFILE_PATH}" \
                     --build-arg BASEIMAGE="${BASEIMAGE}" \
@@ -188,7 +197,11 @@ main() {
                     ${FEATURES_VSCODE:+--build-arg ARG_FINAL_STAGE_BASE="stage_vscode"} \
                     \
                 -t "${DOCKER_REPO}":"${DOCKER_TAG}" "${_build_context}"
+            
+            exit_code=$?
             set +x
+            
+            if [[ ${exit_code} -ne 0 ]] ; then die "Failed to build image '${DOCKER_REPO}:${DOCKER_TAG}'" ${exit_code} ; fi
             ;;
 
         ### -------------------------
@@ -197,8 +210,8 @@ main() {
 
         vscode | vscode-* )
 
+            ### no quotes around ${params}!
             set -x
-            ### no quotes around 'params'
             docker build ${params} \
                 -f "${DOCKERFILE_PATH}" \
                     --build-arg BASEIMAGE="${BASEIMAGE}" \
@@ -228,7 +241,11 @@ main() {
                     ${FEATURES_VSCODE:+--build-arg ARG_FINAL_STAGE_BASE="stage_vscode"} \
                     \
                 -t "${DOCKER_REPO}":"${DOCKER_TAG}" "${_build_context}"
+            
+            exit_code=$?
             set +x
+            
+            if [[ ${exit_code} -ne 0 ]] ; then die "Failed to build image '${DOCKER_REPO}:${DOCKER_TAG}'" ${exit_code} ; fi
             ;;
 
         * )
diff --git a/docker/hooks/pre_build b/docker/hooks/pre_build
--- a/docker/hooks/pre_build
+++ b/docker/hooks/pre_build
@@ -66,8 +66,8 @@ main() {
 
         nodejs | nodejs-* | nodejs-current | nodejs-current-* )
 
+            ### no quotes around ${params}!
             set -x
-            ### no quotes around 'params'
             docker build ${params} \
                 -f "${DOCKERFILE_PATH}" \
                     --build-arg BASEIMAGE="${BASEIMAGE}" \
@@ -97,7 +97,11 @@ main() {
                     ${FEATURES_VSCODE:+--build-arg ARG_FINAL_STAGE_BASE="stage_vscode"} \
                     \
                 -t "${DOCKER_REPO}":"${DOCKER_TAG}${helper_suffix}" "${_build_context}"
+            
+            exit_code=$?
             set +x
+
+            if [[ ${exit_code} -ne 0 ]] ; then set +x; die "Failed to build image '${DOCKER_REPO}:${DOCKER_TAG}${helper_suffix}'" ${exit_code} ; fi
             ;;
 
         ### --------------------------
@@ -106,8 +110,8 @@ main() {
 
         postman | postman-* )
 
+            ### no quotes around ${params}!
             set -x
-            ### no quotes around 'params'
             docker build ${params} \
                 -f "${DOCKERFILE_PATH}" \
                     --build-arg BASEIMAGE="${BASEIMAGE}" \
@@ -135,7 +139,11 @@ main() {
                     ${FEATURES_POSTMAN:+--build-arg ARG_FINAL_STAGE_BASE="stage_postman"} \
                     \
                 -t "${DOCKER_REPO}":"${DOCKER_TAG}${helper_suffix}" "${_build_context}"
+            
+            exit_code=$?
             set +x
+
+            if [[ ${exit_code} -ne 0 ]] ; then die "Failed to build image '${DOCKER_REPO}:${DOCKER_TAG}${helper_suffix}'" ${exit_code} ; fi
             ;;
 
         ### -------------------------
@@ -144,8 +152,8 @@ main() {
 
         python | python-* )
 
+            ### no quotes around ${params}!
             set -x
-            ### no quotes around 'params'
             docker build ${params} \
                 -f "${DOCKERFILE_PATH}" \
                     --build-arg BASEIMAGE="${BASEIMAGE}" \
@@ -173,7 +181,11 @@ main() {
                     ${FEATURES_VSCODE:+--build-arg ARG_FINAL_STAGE_BASE="stage_vscode"} \
                     \
                 -t "${DOCKER_REPO}":"${DOCKER_TAG}${helper_suffix}" "${_build_context}"
+            
+            exit_code=$?
             set +x
+
+            if [[ ${exit_code} -ne 0 ]] ; then die "Failed to build image '${DOCKER_REPO}:${DOCKER_TAG}${helper_suffix}'" ${exit_code} ; fi
             ;;
 
         ### -------------------------
@@ -182,8 +194,8 @@ main() {
 
         vscode | vscode-* )
 
+            ### no quotes around ${params}!
             set -x
-            ### no quotes around 'params'
             docker build ${params} \
                 -f "${DOCKERFILE_PATH}" \
                     --build-arg BASEIMAGE="${BASEIMAGE}" \
@@ -209,7 +221,11 @@ main() {
                     ${FEATURES_VSCODE:+--build-arg ARG_FINAL_STAGE_BASE="stage_vscode"} \
                     \
                 -t "${DOCKER_REPO}":"${DOCKER_TAG}${helper_suffix}" "${_build_context}"
+            
+            exit_code=$?
             set +x
+            
+            if [[ ${exit_code} -ne 0 ]] ; then die "Failed to build image '${DOCKER_REPO}:${DOCKER_TAG}${helper_suffix}'" ${exit_code} ; fi
             ;;
 
         * )
