first G3v2 milestone release

diff --git a/docker/hooks/build b/docker/hooks/build
--- a/docker/hooks/build
+++ b/docker/hooks/build
@@ -1,20 +1,31 @@
 #!/bin/bash -e
 
+echo -e "\n==> EXECUTING @$(date -u +'%Y-%m-%d_%H-%M-%S'): ${0} $@\n"
+
 declare _mydir=$(dirname $0)
 source "${_mydir}"/env.rc
 source "${_mydir}"/util.rc
 
 main() {
+    local now
+    local version_sticker
+    local cache_script="cache"
+    local -i exit_code=0
 
-    if [ -f "${_build_context}/${_scrap_demand_stop_building}" ] ; then
+    if [[ -f "${_build_context}/${_scrap_demand_stop_building}" ]] ; then
+    
         echo "Skipping build on demand."
         return 0
     fi
 
-    local now
-    local version_sticker
+    ### refresh local cache for the case the 'pre_build' was not run
+    "${_mydir}/${cache_script}" "${_branch}" "${_blend}"
+    exit_code=$?
+    if [[ ${exit_code} -ne 0 ]] ; then die "Script '${cache_script}' failed with code ${exit_code}." ${exit_code} ; fi
 
-    if [ -f "${_build_context}/${_scrap_version_sticker_current}" ] ; then
+    ### get current version sticker
+    if [[ -f "${_build_context}/${_scrap_version_sticker_current}" ]] ; then
+
         version_sticker="$( cat ${_build_context}/${_scrap_version_sticker_current} )"
     else
         version_sticker="null"
@@ -47,54 +58,23 @@ main() {
                     ${FEATURES_THUMBNAILING:+--build-arg ARG_FEATURES_THUMBNAILING=1} \
                     ${FEATURES_USER_GROUP_OVERRIDE:+--build-arg ARG_FEATURES_USER_GROUP_OVERRIDE=1} \
                     \
+                    ${FEATURES_VNC:+--build-arg ARG_TIGERVNC_DISTRO=${TIGERVNC_DISTRO}} \
+                    ${FEATURES_VNC:+--build-arg ARG_TIGERVNC_VERSION=${TIGERVNC_VERSION}} \
+                    \
+                    ${FEATURES_NOVNC:+--build-arg ARG_NOVNC_VERSION=${NOVNC_VERSION}} \
+                    ${FEATURES_NOVNC:+--build-arg ARG_WEBSOCKIFY_VERSION=${WEBSOCKIFY_VERSION}} \
                     ${FEATURES_NOVNC:+--build-arg ARG_MERGE_STAGE_VNC_BASE="stage_novnc"} \
                     \
+                    ${FEATURES_CHROMIUM:+--build-arg ARG_CHROMIUM_DISTRO=${CHROMIUM_DISTRO}} \
                     ${FEATURES_CHROMIUM:+--build-arg ARG_CHROMIUM_VERSION=${CHROMIUM_VERSION}} \
                     ${FEATURES_CHROMIUM:+--build-arg ARG_MERGE_STAGE_BROWSER_BASE="stage_chromium"} \
                     \
                     ${FEATURES_FIREFOX:+--build-arg ARG_MERGE_STAGE_BROWSER_BASE="stage_firefox"} \
                     ${FEATURES_FIREFOX_PLUS:+--build-arg ARG_MERGE_STAGE_BROWSER_BASE="stage_firefox_plus"} \
                     \
-                    ${NODEJS_VERSION:+--build-arg ARG_NODEJS_VERSION=${NODEJS_VERSION}} \
+                    ${FEATURES_NODEJS:+--build-arg ARG_NODEJS_DISTRO=${NODEJS_DISTRO}} \
+                    ${FEATURES_NODEJS:+--build-arg ARG_NODEJS_VERSION=${NODEJS_VERSION}} \
                     ${FEATURES_NODEJS:+--build-arg ARG_FINAL_STAGE_BASE="stage_nodejs"} \
-                    \
-                    ${FEATURES_VSCODE:+--build-arg ARG_FINAL_STAGE_BASE="stage_vscode"} \
-                    \
-                -t "${DOCKER_REPO}":"${DOCKER_TAG}" "${_build_context}"
-            set +x
-            ;;
-
-        ### -------------------------
-        ### ubuntu-vnc-xfce-python-g3
-        ### -------------------------
-
-        python | python-* )
-
-            set -x
-            docker build $@ \
-                -f "${DOCKERFILE_PATH}" \
-                    --build-arg BUILDKIT_INLINE_CACHE=1 \
-                    --build-arg BASEIMAGE="${BASEIMAGE}" \
-                    --build-arg BASETAG="${BASETAG}" \
-                    --build-arg ARG_CREATED="${now}" \
-                    --build-arg ARG_DOCKER_TAG=${DOCKER_TAG} \
-                    --build-arg ARG_VERSION_STICKER="${version_sticker}" \
-                    --build-arg ARG_VCS_REF="$(git rev-parse --short HEAD)" \
-                    \
-                    ${FEATURES_BUILD_SLIM:+--build-arg ARG_APT_NO_RECOMMENDS=1} \
-                    ${FEATURES_SCREENSHOOTING:+--build-arg ARG_FEATURES_SCREENSHOOTING=1} \
-                    ${FEATURES_THUMBNAILING:+--build-arg ARG_FEATURES_THUMBNAILING=1} \
-                    ${FEATURES_USER_GROUP_OVERRIDE:+--build-arg ARG_FEATURES_USER_GROUP_OVERRIDE=1} \
-                    \
-                    ${FEATURES_NOVNC:+--build-arg ARG_MERGE_STAGE_VNC_BASE="stage_novnc"} \
-                    \
-                    ${FEATURES_CHROMIUM:+--build-arg ARG_CHROMIUM_VERSION=${CHROMIUM_VERSION}} \
-                    ${FEATURES_CHROMIUM:+--build-arg ARG_MERGE_STAGE_BROWSER_BASE="stage_chromium"} \
-                    \
-                    ${FEATURES_FIREFOX:+--build-arg ARG_MERGE_STAGE_BROWSER_BASE="stage_firefox"} \
-                    ${FEATURES_FIREFOX_PLUS:+--build-arg ARG_MERGE_STAGE_BROWSER_BASE="stage_firefox_plus"} \
-                    \
-                    ${FEATURES_PYTHON:+--build-arg ARG_FINAL_STAGE_BASE="stage_python"} \
                     \
                     ${FEATURES_VSCODE:+--build-arg ARG_FINAL_STAGE_BASE="stage_vscode"} \
                     \
@@ -124,27 +104,33 @@ main() {
                     ${FEATURES_THUMBNAILING:+--build-arg ARG_FEATURES_THUMBNAILING=1} \
                     ${FEATURES_USER_GROUP_OVERRIDE:+--build-arg ARG_FEATURES_USER_GROUP_OVERRIDE=1} \
                     \
+                    ${FEATURES_VNC:+--build-arg ARG_TIGERVNC_DISTRO=${TIGERVNC_DISTRO}} \
+                    ${FEATURES_VNC:+--build-arg ARG_TIGERVNC_VERSION=${TIGERVNC_VERSION}} \
+                    \
+                    ${FEATURES_NOVNC:+--build-arg ARG_NOVNC_VERSION=${NOVNC_VERSION}} \
+                    ${FEATURES_NOVNC:+--build-arg ARG_WEBSOCKIFY_VERSION=${WEBSOCKIFY_VERSION}} \
                     ${FEATURES_NOVNC:+--build-arg ARG_MERGE_STAGE_VNC_BASE="stage_novnc"} \
                     \
+                    ${FEATURES_CHROMIUM:+--build-arg ARG_CHROMIUM_DISTRO=${CHROMIUM_DISTRO}} \
                     ${FEATURES_CHROMIUM:+--build-arg ARG_CHROMIUM_VERSION=${CHROMIUM_VERSION}} \
                     ${FEATURES_CHROMIUM:+--build-arg ARG_MERGE_STAGE_BROWSER_BASE="stage_chromium"} \
                     \
                     ${FEATURES_FIREFOX:+--build-arg ARG_MERGE_STAGE_BROWSER_BASE="stage_firefox"} \
                     ${FEATURES_FIREFOX_PLUS:+--build-arg ARG_MERGE_STAGE_BROWSER_BASE="stage_firefox_plus"} \
                     \
+                    ${FEATURES_POSTMAN:+--build-arg ARG_POSTMAN_DISTRO=${POSTMAN_DISTRO}} \
+                    ${FEATURES_POSTMAN:+--build-arg ARG_POSTMAN_VERSION=${POSTMAN_VERSION}} \
                     ${FEATURES_POSTMAN:+--build-arg ARG_FINAL_STAGE_BASE="stage_postman"} \
                     \
                 -t "${DOCKER_REPO}":"${DOCKER_TAG}" "${_build_context}"
             set +x
             ;;
-            
-        ### --------------------------------
-        ### headless-coding-g3 (base images)
-        ### --------------------------------
 
-        ### These base images will not be built or published on Docker Hub.
+        ### -------------------------
+        ### ubuntu-vnc-xfce-python-g3
+        ### -------------------------
 
-        coding | coding-* )
+        python | python-* )
 
             set -x
             docker build $@ \
@@ -162,23 +148,34 @@ main() {
                     ${FEATURES_THUMBNAILING:+--build-arg ARG_FEATURES_THUMBNAILING=1} \
                     ${FEATURES_USER_GROUP_OVERRIDE:+--build-arg ARG_FEATURES_USER_GROUP_OVERRIDE=1} \
                     \
+                    ${FEATURES_VNC:+--build-arg ARG_TIGERVNC_DISTRO=${TIGERVNC_DISTRO}} \
+                    ${FEATURES_VNC:+--build-arg ARG_TIGERVNC_VERSION=${TIGERVNC_VERSION}} \
+                    \
+                    ${FEATURES_NOVNC:+--build-arg ARG_NOVNC_VERSION=${NOVNC_VERSION}} \
+                    ${FEATURES_NOVNC:+--build-arg ARG_WEBSOCKIFY_VERSION=${WEBSOCKIFY_VERSION}} \
                     ${FEATURES_NOVNC:+--build-arg ARG_MERGE_STAGE_VNC_BASE="stage_novnc"} \
                     \
+                    ${FEATURES_CHROMIUM:+--build-arg ARG_CHROMIUM_DISTRO=${CHROMIUM_DISTRO}} \
                     ${FEATURES_CHROMIUM:+--build-arg ARG_CHROMIUM_VERSION=${CHROMIUM_VERSION}} \
                     ${FEATURES_CHROMIUM:+--build-arg ARG_MERGE_STAGE_BROWSER_BASE="stage_chromium"} \
                     \
                     ${FEATURES_FIREFOX:+--build-arg ARG_MERGE_STAGE_BROWSER_BASE="stage_firefox"} \
                     ${FEATURES_FIREFOX_PLUS:+--build-arg ARG_MERGE_STAGE_BROWSER_BASE="stage_firefox_plus"} \
                     \
+                    ${FEATURES_PYTHON:+--build-arg ARG_FINAL_STAGE_BASE="stage_python"} \
+                    \
+                    ${FEATURES_VSCODE:+--build-arg ARG_FINAL_STAGE_BASE="stage_vscode"} \
+                    \
                 -t "${DOCKER_REPO}":"${DOCKER_TAG}" "${_build_context}"
             set +x
             ;;
 
         * )
-            echo "Cannot build unknown blend '${_blend}'"
-            retutn 1
+            die "Cannot build unknown blend '${_blend}'"
             ;;
     esac
 }
 
 main $@
+
+echo -e "\n==> FINISHED  @$(date -u +'%Y-%m-%d_%H-%M-%S'): ${0} $@\n"
diff --git a/docker/hooks/pre_build b/docker/hooks/pre_build
--- a/docker/hooks/pre_build
+++ b/docker/hooks/pre_build
@@ -1,5 +1,7 @@
 #!/bin/bash -e
 
+echo -e "\n==> EXECUTING @$(date -u +'%Y-%m-%d_%H-%M-%S'): ${0} $@\n"
+
 declare _mydir=$(dirname $0)
 source "${_mydir}"/env.rc
 source "${_mydir}"/util.rc
@@ -8,14 +10,21 @@ main() {
     local helper_suffix="_helper"
     local now
     local version_sticker
+    local -i exit_code=0
 
     local should_build=${FORCE_BUILDING}
     local build_prohibited=${PROHIBIT_BUILDING}
+    local cache_script="cache"
+
+    ### refresh local cache
+    "${_mydir}/${cache_script}" "${_branch}" "${_blend}"
+    exit_code=$?
+    if [[ ${exit_code} -ne 0 ]] ; then die "Script '${cache_script}' failed with code ${exit_code}." ${exit_code} ; fi
 
     ### debugging support
     # dump_environment
 
-    echo "Removing helper files..."
+    echo -e "\nRemoving helper files\n"
     cleanup_scrap_files
 
     ### build a temporary helper image for getting the current version sticker values
@@ -40,50 +49,23 @@ main() {
                     ${FEATURES_THUMBNAILING:+--build-arg ARG_FEATURES_THUMBNAILING=1} \
                     ${FEATURES_USER_GROUP_OVERRIDE:+--build-arg ARG_FEATURES_USER_GROUP_OVERRIDE=1} \
                     \
+                    ${FEATURES_VNC:+--build-arg ARG_TIGERVNC_DISTRO=${TIGERVNC_DISTRO}} \
+                    ${FEATURES_VNC:+--build-arg ARG_TIGERVNC_VERSION=${TIGERVNC_VERSION}} \
+                    \
+                    ${FEATURES_NOVNC:+--build-arg ARG_NOVNC_VERSION=${NOVNC_VERSION}} \
+                    ${FEATURES_NOVNC:+--build-arg ARG_WEBSOCKIFY_VERSION=${WEBSOCKIFY_VERSION}} \
                     ${FEATURES_NOVNC:+--build-arg ARG_MERGE_STAGE_VNC_BASE="stage_novnc"} \
                     \
+                    ${FEATURES_CHROMIUM:+--build-arg ARG_CHROMIUM_DISTRO=${CHROMIUM_DISTRO}} \
                     ${FEATURES_CHROMIUM:+--build-arg ARG_CHROMIUM_VERSION=${CHROMIUM_VERSION}} \
                     ${FEATURES_CHROMIUM:+--build-arg ARG_MERGE_STAGE_BROWSER_BASE="stage_chromium"} \
                     \
                     ${FEATURES_FIREFOX:+--build-arg ARG_MERGE_STAGE_BROWSER_BASE="stage_firefox"} \
                     ${FEATURES_FIREFOX_PLUS:+--build-arg ARG_MERGE_STAGE_BROWSER_BASE="stage_firefox_plus"} \
                     \
-                    ${NODEJS_VERSION:+--build-arg ARG_NODEJS_VERSION=${NODEJS_VERSION}} \
+                    ${FEATURES_NODEJS:+--build-arg ARG_NODEJS_DISTRO=${NODEJS_DISTRO}} \
+                    ${FEATURES_NODEJS:+--build-arg ARG_NODEJS_VERSION=${NODEJS_VERSION}} \
                     ${FEATURES_NODEJS:+--build-arg ARG_FINAL_STAGE_BASE="stage_nodejs"} \
-                    \
-                    ${FEATURES_VSCODE:+--build-arg ARG_FINAL_STAGE_BASE="stage_vscode"} \
-                    \
-                -t "${DOCKER_REPO}":"${DOCKER_TAG}${helper_suffix}" "${_build_context}"
-            set +x
-            ;;
-
-        ### -------------------------
-        ### ubuntu-vnc-xfce-python-g3
-        ### -------------------------
-
-        python | python-* )
-
-            set -x
-            docker build $@ \
-                -f "${DOCKERFILE_PATH}" \
-                    --build-arg BUILDKIT_INLINE_CACHE=1 \
-                    --build-arg BASEIMAGE="${BASEIMAGE}" \
-                    --build-arg BASETAG="${BASETAG}" \
-                    \
-                    ${FEATURES_BUILD_SLIM:+--build-arg ARG_APT_NO_RECOMMENDS=1} \
-                    ${FEATURES_SCREENSHOOTING:+--build-arg ARG_FEATURES_SCREENSHOOTING=1} \
-                    ${FEATURES_THUMBNAILING:+--build-arg ARG_FEATURES_THUMBNAILING=1} \
-                    ${FEATURES_USER_GROUP_OVERRIDE:+--build-arg ARG_FEATURES_USER_GROUP_OVERRIDE=1} \
-                    \
-                    ${FEATURES_NOVNC:+--build-arg ARG_MERGE_STAGE_VNC_BASE="stage_novnc"} \
-                    \
-                    ${FEATURES_CHROMIUM:+--build-arg ARG_CHROMIUM_VERSION=${CHROMIUM_VERSION}} \
-                    ${FEATURES_CHROMIUM:+--build-arg ARG_MERGE_STAGE_BROWSER_BASE="stage_chromium"} \
-                    \
-                    ${FEATURES_FIREFOX:+--build-arg ARG_MERGE_STAGE_BROWSER_BASE="stage_firefox"} \
-                    ${FEATURES_FIREFOX_PLUS:+--build-arg ARG_MERGE_STAGE_BROWSER_BASE="stage_firefox_plus"} \
-                    \
-                    ${FEATURES_PYTHON:+--build-arg ARG_FINAL_STAGE_BASE="stage_python"} \
                     \
                     ${FEATURES_VSCODE:+--build-arg ARG_FINAL_STAGE_BASE="stage_vscode"} \
                     \
@@ -109,27 +91,33 @@ main() {
                     ${FEATURES_THUMBNAILING:+--build-arg ARG_FEATURES_THUMBNAILING=1} \
                     ${FEATURES_USER_GROUP_OVERRIDE:+--build-arg ARG_FEATURES_USER_GROUP_OVERRIDE=1} \
                     \
+                    ${FEATURES_VNC:+--build-arg ARG_TIGERVNC_DISTRO=${TIGERVNC_DISTRO}} \
+                    ${FEATURES_VNC:+--build-arg ARG_TIGERVNC_VERSION=${TIGERVNC_VERSION}} \
+                    \
+                    ${FEATURES_NOVNC:+--build-arg ARG_NOVNC_VERSION=${NOVNC_VERSION}} \
+                    ${FEATURES_NOVNC:+--build-arg ARG_WEBSOCKIFY_VERSION=${WEBSOCKIFY_VERSION}} \
                     ${FEATURES_NOVNC:+--build-arg ARG_MERGE_STAGE_VNC_BASE="stage_novnc"} \
                     \
+                    ${FEATURES_CHROMIUM:+--build-arg ARG_CHROMIUM_DISTRO=${CHROMIUM_DISTRO}} \
                     ${FEATURES_CHROMIUM:+--build-arg ARG_CHROMIUM_VERSION=${CHROMIUM_VERSION}} \
                     ${FEATURES_CHROMIUM:+--build-arg ARG_MERGE_STAGE_BROWSER_BASE="stage_chromium"} \
                     \
                     ${FEATURES_FIREFOX:+--build-arg ARG_MERGE_STAGE_BROWSER_BASE="stage_firefox"} \
                     ${FEATURES_FIREFOX_PLUS:+--build-arg ARG_MERGE_STAGE_BROWSER_BASE="stage_firefox_plus"} \
                     \
+                    ${FEATURES_POSTMAN:+--build-arg ARG_POSTMAN_DISTRO=${POSTMAN_DISTRO}} \
+                    ${FEATURES_POSTMAN:+--build-arg ARG_POSTMAN_VERSION=${POSTMAN_VERSION}} \
                     ${FEATURES_POSTMAN:+--build-arg ARG_FINAL_STAGE_BASE="stage_postman"} \
                     \
                 -t "${DOCKER_REPO}":"${DOCKER_TAG}${helper_suffix}" "${_build_context}"
             set +x
             ;;
 
-        ### --------------------------------
-        ### headless-coding-g3 (base images)
-        ### --------------------------------
+        ### -------------------------
+        ### ubuntu-vnc-xfce-python-g3
+        ### -------------------------
 
-        ### These base images will not be built or published on Docker Hub.
-
-        coding | coding-* )
+        python | python-* )
 
             set -x
             docker build $@ \
@@ -143,21 +131,30 @@ main() {
                     ${FEATURES_THUMBNAILING:+--build-arg ARG_FEATURES_THUMBNAILING=1} \
                     ${FEATURES_USER_GROUP_OVERRIDE:+--build-arg ARG_FEATURES_USER_GROUP_OVERRIDE=1} \
                     \
+                    ${FEATURES_VNC:+--build-arg ARG_TIGERVNC_DISTRO=${TIGERVNC_DISTRO}} \
+                    ${FEATURES_VNC:+--build-arg ARG_TIGERVNC_VERSION=${TIGERVNC_VERSION}} \
+                    \
+                    ${FEATURES_NOVNC:+--build-arg ARG_NOVNC_VERSION=${NOVNC_VERSION}} \
+                    ${FEATURES_NOVNC:+--build-arg ARG_WEBSOCKIFY_VERSION=${WEBSOCKIFY_VERSION}} \
                     ${FEATURES_NOVNC:+--build-arg ARG_MERGE_STAGE_VNC_BASE="stage_novnc"} \
                     \
+                    ${FEATURES_CHROMIUM:+--build-arg ARG_CHROMIUM_DISTRO=${CHROMIUM_DISTRO}} \
                     ${FEATURES_CHROMIUM:+--build-arg ARG_CHROMIUM_VERSION=${CHROMIUM_VERSION}} \
                     ${FEATURES_CHROMIUM:+--build-arg ARG_MERGE_STAGE_BROWSER_BASE="stage_chromium"} \
                     \
                     ${FEATURES_FIREFOX:+--build-arg ARG_MERGE_STAGE_BROWSER_BASE="stage_firefox"} \
                     ${FEATURES_FIREFOX_PLUS:+--build-arg ARG_MERGE_STAGE_BROWSER_BASE="stage_firefox_plus"} \
                     \
+                    ${FEATURES_PYTHON:+--build-arg ARG_FINAL_STAGE_BASE="stage_python"} \
+                    \
+                    ${FEATURES_VSCODE:+--build-arg ARG_FINAL_STAGE_BASE="stage_vscode"} \
+                    \
                 -t "${DOCKER_REPO}":"${DOCKER_TAG}${helper_suffix}" "${_build_context}"
             set +x
             ;;
 
         * )
-            echo "Cannot build unknown blend '${_blend}'"
-            return 1
+            die "Cannot build unknown blend '${_blend}'"
             ;;
     esac
 
@@ -168,7 +165,7 @@ main() {
     echo "${version_sticker}" > "${_build_context}/${_scrap_version_sticker_verbose_current}"
     echo -e "Current verbose version sticker:\n$( cat ${_build_context}/${_scrap_version_sticker_verbose_current} )"
 
-    if [ "${should_build}" == "1" ] ; then
+    if [[ "${should_build}" == "1" ]] ; then
 
         echo ; echo "Building of new image has been forced."
 
@@ -176,8 +173,8 @@ main() {
 
         echo; echo "Building of new image has not been forced."
 
-        echo "Getting the previous verbose version sticker value from the builder repository gist..."
-        if [ -n "${GIST_ID}" ] ; then
+        echo "Getting the previous verbose version sticker value from the builder gist '${GIST_ID}'"
+        if [[ -n "${GIST_ID}" ]] ; then
 
             get_gist_file "${GIST_ID}" "${DOCKER_REPO}" "${DOCKER_TAG}" "version-sticker-verbose.txt" "${_build_context}/${_scrap_version_sticker_verbose_previous}"
 
@@ -186,14 +183,14 @@ main() {
             echo -n "" > "${_build_context}/${_scrap_version_sticker_verbose_previous}"
         fi
 
-        echo "Comparing verbose version stickers..."
+        echo "Comparing verbose version stickers"
         if cmp -s "${_build_context}/${_scrap_version_sticker_verbose_current}" "${_build_context}/${_scrap_version_sticker_verbose_previous}" ; then
 
             ### verbose version sticker hasn't changed since the last build - stop building
             echo "Verbose version sticker has not changed since the last build, no need for building a new image." ; echo
 
             ### if this file is present, the building will not continue
-            echo "Demanding building stop..."
+            echo "Demanding building stop"
             touch "${_build_context}/${_scrap_demand_stop_building}"
 
         else
@@ -213,21 +210,23 @@ main() {
     ### metadata label value 'any.accetto.version-sticker' is filled from this file
     echo -n "${VERSION_STICKER_PREFIX}${version_sticker}${VERSION_STICKER_SUFFIX}" > "${_build_context}/${_scrap_version_sticker_current}"
 
-    ### building prohibitid by environment variable
+    ### building prohibitdd by environment variable
     ### useful for testing the autobuilding on DockerHub before release
-    if [ "${should_build}" == "1" ] && [ "${build_prohibited}" == "1" ] ; then
+    if [[ "${should_build}" == "1" && "${build_prohibited}" == "1" ]] ; then
         ### if this file is present, the building will not continue
-        echo "Building has been prohibited. Demanding building stop..."
+        echo "Building has been prohibited. Demanding building stop"
         echo
         touch "${_build_context}/${_scrap_demand_stop_building}"
     fi
 
     ### display the actual short version sticker
-    echo "Current version sticker: ${VERSION_STICKER_PREFIX}${version_sticker}${VERSION_STICKER_SUFFIX}"
+    echo "Current version sticker of '${DOCKER_REPO}:${DOCKER_TAG}${helper_suffix}': ${VERSION_STICKER_PREFIX}${version_sticker}${VERSION_STICKER_SUFFIX}"
 
     ### delete the helper image in any case
-    echo; echo "Removing helper image..."
+    echo; echo "Removing helper image"
     docker rmi "${DOCKER_REPO}":"${DOCKER_TAG}${helper_suffix}"
 }
 
 main $@
+
+echo -e "\n==> FINISHED  @$(date -u +'%Y-%m-%d_%H-%M-%S'): ${0} $@\n"
